const para = [
    "Delhi is a crowded city. There are very few rich people who travel by their own vehicles. The majority of the people cannot afford to hire a taxi or a three-wheeler. They have to depend on D.T.C. buses, which are the cheapest mode of conveyance. D.T.C. buses are like blood capillaries of our body spreading all over in Delhi. One day I had to go to railway station to receive my uncle. I had to reach there by 9.30 a.m. knowing the irregularity of D.T.C. bus service; I left my home at 7.30 a.m. and reached the bus stop. There was a long queue. Everybody was waiting for the bus but the buses were passing one after another without stopping. I kept waiting for about an hour. I was feeling very restless and I was afraid that I might not be able to reach the station in time. It was 8.45. Luckily a bus stopped just in front of me. It was overcrowded but somehow I managed to get into the bus.",
    "Some passengers were hanging on the footboard, so there was no question of getting a seat. It was very uncomfortable. We were feeling suffocated. All of a sudden, an old man declared that his pocket had been picked. He accused the man standing beside him. The young man took a knife out of his pocket and waved it in the air. No body dared to catch him. I thanked God when the bus stopped at the railway station. I reached there just in time.",
    "The proverb has deep meaning, which is always useful for a successful life. It conveys the idea that we should always think and then act accordingly. Impulsive actions may lead us to embarrassing and odd situations. As we should always think before we speak, in the same way we should think before we act. Life is full of various factors, the factors which can fascinate us for the moment but may lead us to failure or the factors which can repel immediately but may be the stepping stones to success. ",
    "For example, going to a movie or playing video games may seem an attractive thing for the time being but can, in the course of time not only disturb one’s studies but also injure our eyes. Therefore, we should always restrain our intuitive and impulsive desires and then act according to what our mind says is right. Even the great men like Gandhi. Nehru, John Kennedy have been prey to their passions and emotions due to which the nations suffered. We should learn from their lives and should always act thoughtfully.",
    "There are many intelligent people in the economic field who would tell us that rising of prices is a phenomenon, which is characteristic of a developing economy. But inflation can be beneficial only if production and national income of the country also increase. But in our country, national income and production do not increase in proportion to the rise in price due to various diverse factors. Since independence, India faced such problems that in spite of major steps taken to improve the economy, our economy has not come up to our expectations. India was attacked by Pakistan and then China in the earlier years of her freedom.",
    "It took years to recover from the heavy losses of the war. Then large-scale industries, like Iron and Steel showed losses in earlier stages. This also caused hike in price. Nowadays the main reason behind this unbalanced gallop in price is black money. Government is trying hard to control prices by coming down heavily on corrupt officers. It’s taking proper steps to control prices which are causing economic hardships in a commoner’s life. But all these measures will take time to show results. At present the rising of prices is a painful reality which cannot be avoided in our day to day life.",
    "Simple living said the Prophet Mohammed “sets my heart on higher thoughts.” There is a need to follow simplicity in our life. In today’s world of increasing pomp and show, when everybody is joining the rat race of displaying his wealth, we should prefer to live simply, without any artificiality. Mahatma Gandhi’s life shows us that simplicity in life always encourages maturity of mind. Instead of wasting wealth in various socio-religious ceremonies, we should be decent and undemonstrative. People who are really good need not show that they are good.",
    "In the same manner, the sophistication of our life style needs no raw display of wealth, it would rather appear in our character or in the manner we carry ourselves. People, who work hard and are the best servants of humanity, live in a quiet frugal manner. We should consider it a sin to waste money when we are aware of the fact that millions of our compatriots are living below the poverty line. Nowadays, in increasing consumerist culture, where everything is on sale, we should adhere to the simple way of life if we want to preserve human attributes in us.",
    "A few days ago I went to see an interesting football match played between the D.A.V. Higher Secondary School, Karnal and the Govt. Higher Secondary School, Shahabad on the grounds of the S.D. Higher Secondary School, Karnal. A large crowd of students and men from the town were present to cheer up the players. The match began at 4.30 p.m. About five minutes before the fixed time, the referee called upon the captains of the two teams to toss for sides. The D.A.V.’s won the toss. Soon after, the referee blew the whistle and the players took their positions. At another loud whistle, the center forward of the local school picked the ball and the play began. From the very start, the Govt. School team took the offensive.",
    "A few days ago I went to see an interesting football match played between the D.A.V. Higher Secondary School, Karnal and the Govt. Higher Secondary School, Shahabad on the grounds of the S.D. Higher Secondary School, Karnal. A large crowd of students and men from the town were present to cheer up the players. The match began at 4.30 p.m. About five minutes before the fixed time, the referee called upon the captains of the two teams to toss for sides. The D.A.V.’s won the toss. Soon after, the referee blew the whistle and the players took their positions. At another loud whistle, the center forward of the local school picked the ball and the play began. From the very start, the Govt. School team took the offensive.",
    "This is the paragraph.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."

]